-- ==========================================================
-- CREATE TABLE division_mappings AND SEED INITIAL MAPPINGS
-- ==========================================================

CREATE TABLE IF NOT EXISTS public.division_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    division TEXT UNIQUE NOT NULL,
    gl TEXT NOT NULL,
    cc TEXT NOT NULL,
    fa TEXT NOT NULL,
    fund TEXT NOT NULL,
    io TEXT
);

-- Seed initial default mappings from the screenshot/code
INSERT INTO public.division_mappings (division, gl, cc, fa, fund, io) VALUES
  ('RPD', '504046', '816232', '4301', '8110', ''),
  ('RAD', '504046', '816232', '4321', '8110', ''),
  ('IAD', '504046', '816232', '4341', '8110', ''),
  ('ID',  '504046', '816232', '4361', '8110', '')
ON CONFLICT (division) DO NOTHING;
