-- ==========================================================
-- CREATE TABLE division_mappings AND SEED INITIAL MAPPINGS
-- ==========================================================

DROP TABLE IF EXISTS public.division_mappings CASCADE;

CREATE TABLE public.division_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language TEXT NOT NULL,
    division TEXT NOT NULL,
    gl TEXT NOT NULL,
    cc TEXT NOT NULL,
    fa TEXT NOT NULL,
    fund TEXT NOT NULL,
    io TEXT,
    CONSTRAINT uq_division_mappings_language_division UNIQUE (language, division)
);

-- Seed initial default mappings for both EN and FR
INSERT INTO public.division_mappings (language, division, gl, cc, fa, fund, io) VALUES
  ('EN', 'RPD', '504046', '816232', '4301', '8110', ''),
  ('EN', 'RAD', '504046', '816232', '4321', '8110', ''),
  ('EN', 'IAD', '504046', '816232', '4341', '8110', ''),
  ('EN', 'ID',  '504046', '816232', '4361', '8110', ''),
  ('FR', 'RPD', '504046', '816232', '4301', '8110', ''),
  ('FR', 'RAD', '504046', '816232', '4321', '8110', ''),
  ('FR', 'IAD', '504046', '816232', '4341', '8110', ''),
  ('FR', 'ID',  '504046', '816232', '4361', '8110', '')
ON CONFLICT (language, division) DO NOTHING;

-- ==========================================================
-- RLS POLICIES FOR division_mappings
-- ==========================================================

-- Enable RLS
ALTER TABLE public.division_mappings ENABLE ROW LEVEL SECURITY;

-- Policy to allow authenticated users to read mappings
CREATE POLICY "Allow authenticated users to read division mappings" 
ON public.division_mappings
FOR SELECT 
TO authenticated
USING (true);

-- Policy to allow admin and manager roles to modify mappings
CREATE POLICY "Allow admin and manager to modify division mappings" 
ON public.division_mappings
FOR ALL
TO authenticated
USING (
  ((auth.jwt() -> 'user_roles'::text) ? 'admin'::text) OR 
  ((auth.jwt() -> 'user_roles'::text) ? 'manager'::text)
)
WITH CHECK (
  ((auth.jwt() -> 'user_roles'::text) ? 'admin'::text) OR 
  ((auth.jwt() -> 'user_roles'::text) ? 'manager'::text)
);
